theme: jekyll-theme-minimal
title: Dr. Yulia Grishina
description: Research Scientist at Amazon Alexa<br> <a href="mailto:yuliag@amazon.com">yuliag@amazon.com</a>
show_downloads: false
github:
  is_user_page: true
