theme: jekyll-theme-minimal
title: Dr. Yulia Grishina
description: Applied Scientist at Amazon AGI<br> Berlin, Germany<br> <a href="mailto:yuliag@amazon.com">yuliag@amazon.com</a>
show_downloads: false
github:
  is_user_page: true
